# Generated by Django 2.1.7 on 2019-03-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='passing_year',
            field=models.IntegerField(),
        ),
    ]
